version: "3.9"

services:
  rasa:
    build:
      context: https://github.com/ITBusinessClassteam2member/Rasarennkei.git
    ports:
      - "6000:6000"
    volumes:
      - ./rasa:/app/rasa
    environment:
      - RASA_ENV=production

  flask:
    build:
      context: https://github.com/ITBusinessClassteam2member/Rasarennkei.git
    ports:
      - "8000:8000"
    depends_on:
      - rasa
