version: "3.9"

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./Rasa:/app/Rasa
    environment:
      - RASA_ENV=production

  flask:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rasa
