version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rasa

  rasa:
    image: rasa/rasa:3.1.1
    command: run --enable-api --cors "*" --port 5005
    volumes:
      - ./rasa:/app
    ports:
      - "5005:5005"
