version: '3.8'

services:
  rasa:
    build: ./rasa_app
    ports:
      - "5005:5005"
    volumes:
      - ./rasa_app:/app
    networks:
      - rasa_network

  flask:
    build: ./flask_app
    ports:
      - "8000:5000"
    depends_on:
      - rasa
    networks:
      - rasa_network

networks:
  rasa_network:
