version: "3.8"

services:
  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile  # 正しいDockerfileパス
    ports:
      - "5000:5000"
    depends_on:
      - rasa
    networks:
      - app_network

  rasa:
    build:
      context: .
      dockerfile: rasa/Dockerfile  # 正しいDockerfileパス
    ports:
      - "5005:5005"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
