[supervisord]
nodaemon=true

[program:flask]
command=gunicorn -b 0.0.0.0:5000 flask_app.app:app
autostart=true
autorestart=true
stderr_logfile=/dev/stdout
stdout_logfile=/dev/stdout

[program:rasa]
command=rasa run --enable-api --cors "*" --port 5005 --model rasa_app/models
autostart=true
autorestart=true
stderr_logfile=/dev/stdout
stdout_logfile=/dev/stdout
